// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vauchi_mobileFFI)
import vauchi_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vauchi_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vauchi_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Main Vauchi interface for mobile platforms.
 *
 * Uses on-demand storage connections for thread safety.
 */
public protocol VauchiMobileProtocol : AnyObject {
    
    /**
     * Add field to own card.
     */
    func addField(fieldType: MobileFieldType, label: String, value: String) throws 
    
    /**
     * Complete exchange with scanned QR data.
     */
    func completeExchange(qrData: String) throws  -> MobileExchangeResult
    
    /**
     * Get contact count.
     */
    func contactCount() throws  -> UInt32
    
    /**
     * Create a new identity.
     */
    func createIdentity(displayName: String) throws 
    
    /**
     * Export encrypted backup.
     */
    func exportBackup(password: String) throws  -> String
    
    /**
     * Generate exchange QR data.
     */
    func generateExchangeQr() throws  -> MobileExchangeData
    
    /**
     * Get single contact by ID.
     */
    func getContact(id: String) throws  -> MobileContact?
    
    /**
     * Get display name.
     */
    func getDisplayName() throws  -> String
    
    /**
     * Get own contact card.
     */
    func getOwnCard() throws  -> MobileContactCard
    
    /**
     * Get profile URL for a social field.
     */
    func getProfileUrl(networkId: String, username: String)  -> String?
    
    /**
     * Get public ID.
     */
    func getPublicId() throws  -> String
    
    /**
     * Get sync status.
     */
    func getSyncStatus()  -> MobileSyncStatus
    
    /**
     * Check if identity exists.
     * This checks both in-memory cache and persistent storage.
     */
    func hasIdentity()  -> Bool
    
    /**
     * Hide field from contact.
     */
    func hideFieldFromContact(contactId: String, fieldLabel: String) throws 
    
    /**
     * Import backup.
     */
    func importBackup(backupData: String, password: String) throws 
    
    /**
     * Check if field is visible to contact.
     */
    func isFieldVisibleToContact(contactId: String, fieldLabel: String) throws  -> Bool
    
    /**
     * List all contacts.
     */
    func listContacts() throws  -> [MobileContact]
    
    /**
     * List available social networks.
     */
    func listSocialNetworks()  -> [MobileSocialNetwork]
    
    /**
     * Get pending update count.
     */
    func pendingUpdateCount() throws  -> UInt32
    
    /**
     * Remove contact.
     */
    func removeContact(id: String) throws  -> Bool
    
    /**
     * Remove field from card.
     */
    func removeField(label: String) throws  -> Bool
    
    /**
     * Search contacts.
     */
    func searchContacts(query: String) throws  -> [MobileContact]
    
    /**
     * Search social networks.
     */
    func searchSocialNetworks(query: String)  -> [MobileSocialNetwork]
    
    /**
     * Set display name.
     */
    func setDisplayName(name: String) throws 
    
    /**
     * Show field to contact.
     */
    func showFieldToContact(contactId: String, fieldLabel: String) throws 
    
    /**
     * Sync with relay server.
     *
     * Connects to the configured relay, sends pending updates,
     * and receives incoming updates from contacts.
     */
    func sync() throws  -> MobileSyncResult
    
    /**
     * Update field value.
     */
    func updateField(label: String, newValue: String) throws 
    
    /**
     * Verify contact fingerprint.
     */
    func verifyContact(id: String) throws 
    
}

/**
 * Main Vauchi interface for mobile platforms.
 *
 * Uses on-demand storage connections for thread safety.
 */
open class VauchiMobile:
    VauchiMobileProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_vauchi_mobile_fn_clone_vauchimobile(self.pointer, $0) }
    }
    /**
     * Create a new VauchiMobile instance.
     */
public convenience init(dataDir: String, relayUrl: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_constructor_vauchimobile_new(
        FfiConverterString.lower(dataDir),
        FfiConverterString.lower(relayUrl),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_vauchi_mobile_fn_free_vauchimobile(pointer, $0) }
    }

    

    
    /**
     * Add field to own card.
     */
open func addField(fieldType: MobileFieldType, label: String, value: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_add_field(self.uniffiClonePointer(),
        FfiConverterTypeMobileFieldType.lower(fieldType),
        FfiConverterString.lower(label),
        FfiConverterString.lower(value),$0
    )
}
}
    
    /**
     * Complete exchange with scanned QR data.
     */
open func completeExchange(qrData: String)throws  -> MobileExchangeResult {
    return try  FfiConverterTypeMobileExchangeResult.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_complete_exchange(self.uniffiClonePointer(),
        FfiConverterString.lower(qrData),$0
    )
})
}
    
    /**
     * Get contact count.
     */
open func contactCount()throws  -> UInt32 {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_contact_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Create a new identity.
     */
open func createIdentity(displayName: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_create_identity(self.uniffiClonePointer(),
        FfiConverterString.lower(displayName),$0
    )
}
}
    
    /**
     * Export encrypted backup.
     */
open func exportBackup(password: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_export_backup(self.uniffiClonePointer(),
        FfiConverterString.lower(password),$0
    )
})
}
    
    /**
     * Generate exchange QR data.
     */
open func generateExchangeQr()throws  -> MobileExchangeData {
    return try  FfiConverterTypeMobileExchangeData.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_generate_exchange_qr(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get single contact by ID.
     */
open func getContact(id: String)throws  -> MobileContact? {
    return try  FfiConverterOptionTypeMobileContact.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Get display name.
     */
open func getDisplayName()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_display_name(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get own contact card.
     */
open func getOwnCard()throws  -> MobileContactCard {
    return try  FfiConverterTypeMobileContactCard.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_own_card(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get profile URL for a social field.
     */
open func getProfileUrl(networkId: String, username: String) -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_profile_url(self.uniffiClonePointer(),
        FfiConverterString.lower(networkId),
        FfiConverterString.lower(username),$0
    )
})
}
    
    /**
     * Get public ID.
     */
open func getPublicId()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_public_id(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get sync status.
     */
open func getSyncStatus() -> MobileSyncStatus {
    return try!  FfiConverterTypeMobileSyncStatus.lift(try! rustCall() {
    uniffi_vauchi_mobile_fn_method_vauchimobile_get_sync_status(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if identity exists.
     * This checks both in-memory cache and persistent storage.
     */
open func hasIdentity() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_vauchi_mobile_fn_method_vauchimobile_has_identity(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Hide field from contact.
     */
open func hideFieldFromContact(contactId: String, fieldLabel: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_hide_field_from_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterString.lower(fieldLabel),$0
    )
}
}
    
    /**
     * Import backup.
     */
open func importBackup(backupData: String, password: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_import_backup(self.uniffiClonePointer(),
        FfiConverterString.lower(backupData),
        FfiConverterString.lower(password),$0
    )
}
}
    
    /**
     * Check if field is visible to contact.
     */
open func isFieldVisibleToContact(contactId: String, fieldLabel: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_is_field_visible_to_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterString.lower(fieldLabel),$0
    )
})
}
    
    /**
     * List all contacts.
     */
open func listContacts()throws  -> [MobileContact] {
    return try  FfiConverterSequenceTypeMobileContact.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_list_contacts(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * List available social networks.
     */
open func listSocialNetworks() -> [MobileSocialNetwork] {
    return try!  FfiConverterSequenceTypeMobileSocialNetwork.lift(try! rustCall() {
    uniffi_vauchi_mobile_fn_method_vauchimobile_list_social_networks(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get pending update count.
     */
open func pendingUpdateCount()throws  -> UInt32 {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_pending_update_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Remove contact.
     */
open func removeContact(id: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_remove_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Remove field from card.
     */
open func removeField(label: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_remove_field(self.uniffiClonePointer(),
        FfiConverterString.lower(label),$0
    )
})
}
    
    /**
     * Search contacts.
     */
open func searchContacts(query: String)throws  -> [MobileContact] {
    return try  FfiConverterSequenceTypeMobileContact.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_search_contacts(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Search social networks.
     */
open func searchSocialNetworks(query: String) -> [MobileSocialNetwork] {
    return try!  FfiConverterSequenceTypeMobileSocialNetwork.lift(try! rustCall() {
    uniffi_vauchi_mobile_fn_method_vauchimobile_search_social_networks(self.uniffiClonePointer(),
        FfiConverterString.lower(query),$0
    )
})
}
    
    /**
     * Set display name.
     */
open func setDisplayName(name: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_set_display_name(self.uniffiClonePointer(),
        FfiConverterString.lower(name),$0
    )
}
}
    
    /**
     * Show field to contact.
     */
open func showFieldToContact(contactId: String, fieldLabel: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_show_field_to_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(contactId),
        FfiConverterString.lower(fieldLabel),$0
    )
}
}
    
    /**
     * Sync with relay server.
     *
     * Connects to the configured relay, sends pending updates,
     * and receives incoming updates from contacts.
     */
open func sync()throws  -> MobileSyncResult {
    return try  FfiConverterTypeMobileSyncResult.lift(try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_sync(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Update field value.
     */
open func updateField(label: String, newValue: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_update_field(self.uniffiClonePointer(),
        FfiConverterString.lower(label),
        FfiConverterString.lower(newValue),$0
    )
}
}
    
    /**
     * Verify contact fingerprint.
     */
open func verifyContact(id: String)throws  {try rustCallWithError(FfiConverterTypeMobileError.lift) {
    uniffi_vauchi_mobile_fn_method_vauchimobile_verify_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVauchiMobile: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = VauchiMobile

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> VauchiMobile {
        return VauchiMobile(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: VauchiMobile) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VauchiMobile {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: VauchiMobile, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVauchiMobile_lift(_ pointer: UnsafeMutableRawPointer) throws -> VauchiMobile {
    return try FfiConverterTypeVauchiMobile.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVauchiMobile_lower(_ value: VauchiMobile) -> UnsafeMutableRawPointer {
    return FfiConverterTypeVauchiMobile.lower(value)
}


/**
 * Mobile-friendly contact.
 */
public struct MobileContact {
    public var id: String
    public var displayName: String
    public var isVerified: Bool
    public var card: MobileContactCard
    public var addedAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, displayName: String, isVerified: Bool, card: MobileContactCard, addedAt: UInt64) {
        self.id = id
        self.displayName = displayName
        self.isVerified = isVerified
        self.card = card
        self.addedAt = addedAt
    }
}



extension MobileContact: Equatable, Hashable {
    public static func ==(lhs: MobileContact, rhs: MobileContact) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.isVerified != rhs.isVerified {
            return false
        }
        if lhs.card != rhs.card {
            return false
        }
        if lhs.addedAt != rhs.addedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(displayName)
        hasher.combine(isVerified)
        hasher.combine(card)
        hasher.combine(addedAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileContact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileContact {
        return
            try MobileContact(
                id: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                isVerified: FfiConverterBool.read(from: &buf), 
                card: FfiConverterTypeMobileContactCard.read(from: &buf), 
                addedAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileContact, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterBool.write(value.isVerified, into: &buf)
        FfiConverterTypeMobileContactCard.write(value.card, into: &buf)
        FfiConverterUInt64.write(value.addedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContact_lift(_ buf: RustBuffer) throws -> MobileContact {
    return try FfiConverterTypeMobileContact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContact_lower(_ value: MobileContact) -> RustBuffer {
    return FfiConverterTypeMobileContact.lower(value)
}


/**
 * Mobile-friendly contact card.
 */
public struct MobileContactCard {
    public var displayName: String
    public var fields: [MobileContactField]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(displayName: String, fields: [MobileContactField]) {
        self.displayName = displayName
        self.fields = fields
    }
}



extension MobileContactCard: Equatable, Hashable {
    public static func ==(lhs: MobileContactCard, rhs: MobileContactCard) -> Bool {
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.fields != rhs.fields {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(displayName)
        hasher.combine(fields)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileContactCard: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileContactCard {
        return
            try MobileContactCard(
                displayName: FfiConverterString.read(from: &buf), 
                fields: FfiConverterSequenceTypeMobileContactField.read(from: &buf)
        )
    }

    public static func write(_ value: MobileContactCard, into buf: inout [UInt8]) {
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterSequenceTypeMobileContactField.write(value.fields, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContactCard_lift(_ buf: RustBuffer) throws -> MobileContactCard {
    return try FfiConverterTypeMobileContactCard.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContactCard_lower(_ value: MobileContactCard) -> RustBuffer {
    return FfiConverterTypeMobileContactCard.lower(value)
}


/**
 * Mobile-friendly contact field.
 */
public struct MobileContactField {
    public var id: String
    public var fieldType: MobileFieldType
    public var label: String
    public var value: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, fieldType: MobileFieldType, label: String, value: String) {
        self.id = id
        self.fieldType = fieldType
        self.label = label
        self.value = value
    }
}



extension MobileContactField: Equatable, Hashable {
    public static func ==(lhs: MobileContactField, rhs: MobileContactField) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.fieldType != rhs.fieldType {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(fieldType)
        hasher.combine(label)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileContactField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileContactField {
        return
            try MobileContactField(
                id: FfiConverterString.read(from: &buf), 
                fieldType: FfiConverterTypeMobileFieldType.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MobileContactField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterTypeMobileFieldType.write(value.fieldType, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContactField_lift(_ buf: RustBuffer) throws -> MobileContactField {
    return try FfiConverterTypeMobileContactField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileContactField_lower(_ value: MobileContactField) -> RustBuffer {
    return FfiConverterTypeMobileContactField.lower(value)
}


/**
 * Exchange QR data.
 */
public struct MobileExchangeData {
    public var qrData: String
    public var publicId: String
    public var expiresAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(qrData: String, publicId: String, expiresAt: UInt64) {
        self.qrData = qrData
        self.publicId = publicId
        self.expiresAt = expiresAt
    }
}



extension MobileExchangeData: Equatable, Hashable {
    public static func ==(lhs: MobileExchangeData, rhs: MobileExchangeData) -> Bool {
        if lhs.qrData != rhs.qrData {
            return false
        }
        if lhs.publicId != rhs.publicId {
            return false
        }
        if lhs.expiresAt != rhs.expiresAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(qrData)
        hasher.combine(publicId)
        hasher.combine(expiresAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileExchangeData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileExchangeData {
        return
            try MobileExchangeData(
                qrData: FfiConverterString.read(from: &buf), 
                publicId: FfiConverterString.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileExchangeData, into buf: inout [UInt8]) {
        FfiConverterString.write(value.qrData, into: &buf)
        FfiConverterString.write(value.publicId, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileExchangeData_lift(_ buf: RustBuffer) throws -> MobileExchangeData {
    return try FfiConverterTypeMobileExchangeData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileExchangeData_lower(_ value: MobileExchangeData) -> RustBuffer {
    return FfiConverterTypeMobileExchangeData.lower(value)
}


/**
 * Exchange result.
 */
public struct MobileExchangeResult {
    public var contactId: String
    public var contactName: String
    public var success: Bool
    public var errorMessage: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(contactId: String, contactName: String, success: Bool, errorMessage: String?) {
        self.contactId = contactId
        self.contactName = contactName
        self.success = success
        self.errorMessage = errorMessage
    }
}



extension MobileExchangeResult: Equatable, Hashable {
    public static func ==(lhs: MobileExchangeResult, rhs: MobileExchangeResult) -> Bool {
        if lhs.contactId != rhs.contactId {
            return false
        }
        if lhs.contactName != rhs.contactName {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        if lhs.errorMessage != rhs.errorMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(contactId)
        hasher.combine(contactName)
        hasher.combine(success)
        hasher.combine(errorMessage)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileExchangeResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileExchangeResult {
        return
            try MobileExchangeResult(
                contactId: FfiConverterString.read(from: &buf), 
                contactName: FfiConverterString.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: MobileExchangeResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.contactId, into: &buf)
        FfiConverterString.write(value.contactName, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileExchangeResult_lift(_ buf: RustBuffer) throws -> MobileExchangeResult {
    return try FfiConverterTypeMobileExchangeResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileExchangeResult_lower(_ value: MobileExchangeResult) -> RustBuffer {
    return FfiConverterTypeMobileExchangeResult.lower(value)
}


/**
 * Social network info.
 */
public struct MobileSocialNetwork {
    public var id: String
    public var displayName: String
    public var urlTemplate: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, displayName: String, urlTemplate: String) {
        self.id = id
        self.displayName = displayName
        self.urlTemplate = urlTemplate
    }
}



extension MobileSocialNetwork: Equatable, Hashable {
    public static func ==(lhs: MobileSocialNetwork, rhs: MobileSocialNetwork) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.urlTemplate != rhs.urlTemplate {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(displayName)
        hasher.combine(urlTemplate)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileSocialNetwork: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileSocialNetwork {
        return
            try MobileSocialNetwork(
                id: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                urlTemplate: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MobileSocialNetwork, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.urlTemplate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSocialNetwork_lift(_ buf: RustBuffer) throws -> MobileSocialNetwork {
    return try FfiConverterTypeMobileSocialNetwork.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSocialNetwork_lower(_ value: MobileSocialNetwork) -> RustBuffer {
    return FfiConverterTypeMobileSocialNetwork.lower(value)
}


/**
 * Sync result with statistics.
 */
public struct MobileSyncResult {
    /**
     * Number of new contacts added from exchange messages.
     */
    public var contactsAdded: UInt32
    /**
     * Number of contact cards updated.
     */
    public var cardsUpdated: UInt32
    /**
     * Number of outbound updates sent.
     */
    public var updatesSent: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Number of new contacts added from exchange messages.
         */contactsAdded: UInt32, 
        /**
         * Number of contact cards updated.
         */cardsUpdated: UInt32, 
        /**
         * Number of outbound updates sent.
         */updatesSent: UInt32) {
        self.contactsAdded = contactsAdded
        self.cardsUpdated = cardsUpdated
        self.updatesSent = updatesSent
    }
}



extension MobileSyncResult: Equatable, Hashable {
    public static func ==(lhs: MobileSyncResult, rhs: MobileSyncResult) -> Bool {
        if lhs.contactsAdded != rhs.contactsAdded {
            return false
        }
        if lhs.cardsUpdated != rhs.cardsUpdated {
            return false
        }
        if lhs.updatesSent != rhs.updatesSent {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(contactsAdded)
        hasher.combine(cardsUpdated)
        hasher.combine(updatesSent)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileSyncResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileSyncResult {
        return
            try MobileSyncResult(
                contactsAdded: FfiConverterUInt32.read(from: &buf), 
                cardsUpdated: FfiConverterUInt32.read(from: &buf), 
                updatesSent: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MobileSyncResult, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.contactsAdded, into: &buf)
        FfiConverterUInt32.write(value.cardsUpdated, into: &buf)
        FfiConverterUInt32.write(value.updatesSent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSyncResult_lift(_ buf: RustBuffer) throws -> MobileSyncResult {
    return try FfiConverterTypeMobileSyncResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSyncResult_lower(_ value: MobileSyncResult) -> RustBuffer {
    return FfiConverterTypeMobileSyncResult.lower(value)
}


/**
 * Mobile-friendly error type.
 */
public enum MobileError {

    
    
    case NotInitialized
    case AlreadyInitialized
    case IdentityNotFound
    case ContactNotFound(String
    )
    case InvalidQrCode
    case ExchangeFailed(String
    )
    case SyncFailed(String
    )
    case StorageError(String
    )
    case CryptoError(String
    )
    case SerializationError(String
    )
    case NetworkError(String
    )
    case InvalidInput(String
    )
    case Internal(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileError: FfiConverterRustBuffer {
    typealias SwiftType = MobileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotInitialized
        case 2: return .AlreadyInitialized
        case 3: return .IdentityNotFound
        case 4: return .ContactNotFound(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidQrCode
        case 6: return .ExchangeFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .SyncFailed(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .StorageError(
            try FfiConverterString.read(from: &buf)
            )
        case 9: return .CryptoError(
            try FfiConverterString.read(from: &buf)
            )
        case 10: return .SerializationError(
            try FfiConverterString.read(from: &buf)
            )
        case 11: return .NetworkError(
            try FfiConverterString.read(from: &buf)
            )
        case 12: return .InvalidInput(
            try FfiConverterString.read(from: &buf)
            )
        case 13: return .Internal(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotInitialized:
            writeInt(&buf, Int32(1))
        
        
        case .AlreadyInitialized:
            writeInt(&buf, Int32(2))
        
        
        case .IdentityNotFound:
            writeInt(&buf, Int32(3))
        
        
        case let .ContactNotFound(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .InvalidQrCode:
            writeInt(&buf, Int32(5))
        
        
        case let .ExchangeFailed(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SyncFailed(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .StorageError(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .CryptoError(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .SerializationError(v1):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .NetworkError(v1):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidInput(v1):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Internal(v1):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension MobileError: Equatable, Hashable {}

extension MobileError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mobile-friendly field type enum.
 */

public enum MobileFieldType {
    
    case email
    case phone
    case website
    case address
    case social
    case custom
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileFieldType: FfiConverterRustBuffer {
    typealias SwiftType = MobileFieldType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileFieldType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .email
        
        case 2: return .phone
        
        case 3: return .website
        
        case 4: return .address
        
        case 5: return .social
        
        case 6: return .custom
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileFieldType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .email:
            writeInt(&buf, Int32(1))
        
        
        case .phone:
            writeInt(&buf, Int32(2))
        
        
        case .website:
            writeInt(&buf, Int32(3))
        
        
        case .address:
            writeInt(&buf, Int32(4))
        
        
        case .social:
            writeInt(&buf, Int32(5))
        
        
        case .custom:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileFieldType_lift(_ buf: RustBuffer) throws -> MobileFieldType {
    return try FfiConverterTypeMobileFieldType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileFieldType_lower(_ value: MobileFieldType) -> RustBuffer {
    return FfiConverterTypeMobileFieldType.lower(value)
}



extension MobileFieldType: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Sync status.
 */

public enum MobileSyncStatus {
    
    case idle
    case syncing
    case error
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileSyncStatus: FfiConverterRustBuffer {
    typealias SwiftType = MobileSyncStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileSyncStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .syncing
        
        case 3: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileSyncStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .syncing:
            writeInt(&buf, Int32(2))
        
        
        case .error:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSyncStatus_lift(_ buf: RustBuffer) throws -> MobileSyncStatus {
    return try FfiConverterTypeMobileSyncStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileSyncStatus_lower(_ value: MobileSyncStatus) -> RustBuffer {
    return FfiConverterTypeMobileSyncStatus.lower(value)
}



extension MobileSyncStatus: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMobileContact: FfiConverterRustBuffer {
    typealias SwiftType = MobileContact?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMobileContact.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMobileContact.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMobileContact: FfiConverterRustBuffer {
    typealias SwiftType = [MobileContact]

    public static func write(_ value: [MobileContact], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMobileContact.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MobileContact] {
        let len: Int32 = try readInt(&buf)
        var seq = [MobileContact]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMobileContact.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMobileContactField: FfiConverterRustBuffer {
    typealias SwiftType = [MobileContactField]

    public static func write(_ value: [MobileContactField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMobileContactField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MobileContactField] {
        let len: Int32 = try readInt(&buf)
        var seq = [MobileContactField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMobileContactField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMobileSocialNetwork: FfiConverterRustBuffer {
    typealias SwiftType = [MobileSocialNetwork]

    public static func write(_ value: [MobileSocialNetwork], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMobileSocialNetwork.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MobileSocialNetwork] {
        let len: Int32 = try readInt(&buf)
        var seq = [MobileSocialNetwork]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMobileSocialNetwork.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vauchi_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_add_field() != 63870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_complete_exchange() != 1223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_contact_count() != 50309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_create_identity() != 45061) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_export_backup() != 43727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_generate_exchange_qr() != 6386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_contact() != 2017) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_display_name() != 40218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_own_card() != 12870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_profile_url() != 26882) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_public_id() != 32830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_get_sync_status() != 54191) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_has_identity() != 8658) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_hide_field_from_contact() != 16087) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_import_backup() != 14171) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_is_field_visible_to_contact() != 38489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_list_contacts() != 3637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_list_social_networks() != 32928) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_pending_update_count() != 63009) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_remove_contact() != 8075) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_remove_field() != 25817) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_search_contacts() != 44205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_search_social_networks() != 62897) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_set_display_name() != 13638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_show_field_to_contact() != 15396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_sync() != 35543) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_update_field() != 47840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_method_vauchimobile_verify_contact() != 63186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vauchi_mobile_checksum_constructor_vauchimobile_new() != 8085) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all